### ISSUE TITLE
Problem with opening videos

### ISSUE THREAD

**Issue by Jamaika1** [Mr-Ojii/L-SMASH-Works#14]
Hello.
I don't know much about avisynth, but I have a question, is it compatible with ffmpeg 7.1.0?
Is L-smash only compatible in virtualdub which produces modified B-frames?
Why do I have to think about framerate?
```
NOTE: You must explicitly set this if the source is an AVI file that contains null/drop frames that you would like to keep. For
example, AVI files captured using VirtualDub commonly contain null/drop frames that were inserted during the capture process.
Unless you provide this parameter, these null frames will be discarded, commonly resulting in loss of audio/video sync.
```

I'm testing latest avisynth static with latest ffmpeg in GNU 11.5.0 SIMD AVX2. What surprises me?
I realize that this isn't paid editor with video effects.
[https://github.com/HomeOfAviSynthPlu...fa128d190e78fb](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/commit/f41e8d511be8dd124b91e3502dfa128d190e78fb)
[https://github.com/l-smash/l-smash/c...345c72179b8998](https://github.com/l-smash/l-smash/commit/18a9ed25c7ff79a7f4f4bf850c345c72179b8998)
[https://github.com/AviSynth/AviSynth...27622a8b919d06](https://github.com/AviSynth/AviSynthPlus/commit/b7dbabd0c6bd2069e2bb2d31c127622a8b919d06)
[https://github.com/FFmpeg/FFmpeg/com...210bb596b19c2d](https://github.com/FFmpeg/FFmpeg/commit/7b20985d8d886fb32badc94f8d210bb596b19c2d)

Why do I have to convert lossy AVI files in ffmpeg (XviD, X264) so ​​that the LWLibavVideoSource plugin doesn't stutter?
ffmpeg_avx2.exe -i myAvi.avi -c:v libx264 -c:a mp3 -vb 850k -ab 128k 111.avi

LWLibavVideoSource("111.avi", stream_index=-1, cache=true , seek_mode=0, ff_loglevel=6, format="YUV420P8" ).selectevery(2,0)

Edit:
Which library is up to date and correct today. Because I see on github https://github.com/Mr-Ojii/L-SMASH-Works
There are also other git libraries.

Is this necessary? [https://github.com/rwxPOPn/LSW-FFmpe...51180a8f11e5fc](https://github.com/rwxPOPn/LSW-FFmpeg/commit/1e932fce0dbb1d5657ca54cedd51180a8f11e5fc)

Converter ffmpeg 7.1.0
https://www.sendspace.com/file/hxbjj5

Source video
https://www.sendspace.com/file/jtjvyv

???
```
if( codec->pix_fmts )
codecpar->format = (int)avcodec_find_best_pix_fmt_of_list( codec->pix_fmts, pix_fmt, 1, NULL );
```

Code:
```
c:/gcc1150/bin/../lib/gcc/x86_64-w64-mingw32/11.5.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib\lwlibavsource_x64.a(lwlibav_video.o):lwlibav_video.:(.text+0x3263): undefined reference to `avcodec_find_best_pix_fmt_of_list'
```
Code:
```
qsv.c: In function 'is_qsv_decoder':
qsv.c:45:5: warning: 'pix_fmts' is deprecated [-Wdeprecated-declarations]
   45 |     if( codec && codec->pix_fmts )
      |     ^~
In file included from c:\gcc1150\x86_64-w64-mingw32\include\libavcodec\avcodec.h:41,
                 from qsv.c:31:
c:\gcc1150\x86_64-w64-mingw32\include\libavcodec\codec.h:215:31: note: declared here
  215 |     const enum AVPixelFormat *pix_fmts;     ///< @deprecated use avcodec_get_supported_config()
      |                               ^~~~~~~~

```
Test: https://github.com/Mr-Ojii/L-SMASH-Works
Assertion failed: IsString(), file interface.cpp, line 836B

**Comment by Mr-Ojii** [comment]
Hello!
Sorry for the late reply, I've been busy...
I'm using machine translation, so sorry if my English is weird....

1. 
> I don't know much about avisynth, but I have a question, is it compatible with ffmpeg 7.1.0?

Maybe...
I have made changes so that LSW can be built with FFmpeg 7.1, but I have not been able to test much about loading video files.

2.
> Is L-smash only compatible in virtualdub which produces modified B-frames?
> Why do I have to think about framerate?

AVI files can only contain CFR(Constant Frame Rate) video, therefore "null frame" may be inserted if the capture was not completed in time.
The “null frame” has the role of copying the previous frame.
L-SMASH-Works ignores “null frames”, so the frame rate changes.
By specifying the frame rate, it is possible to display one previous frame in the “null frame” timestamp.

3.
> Why do I have to convert lossy AVI files in ffmpeg (XviD, X264) so ​​that the LWLibavVideoSource plugin doesn't stutter?

FFmpeg can convert a “null frame” to a mere frame by converting it.

4. 
> Which library is up to date and correct today. Because I see on github https://github.com/Mr-Ojii/L-SMASH-Works
> There are also other git libraries.

If you want to use plug-in for AviSynth, I recommend using https://github.comHomeOfAviSynthPlusEvolution/L-SMASH-Works.
This repository develops plug-in for AviUtl.

5.
> Is this necessary? https://github.com/rwxPOPn/LSW-FFmpeg/commit/1e932fce0dbb1d5657ca54cedd51180a8f11e5fc

This may be necessary when loading Japanese TV broadcast streams.

**Comment by Jamaika1** [comment]
Thanks for your answer
