### ISSUE TITLE
wmvファイルで初回読み込み時に音声がロードされない

### ISSUE THREAD

**Issue by SysVR** [Mr-Ojii/L-SMASH-Works#4]
・wmvファイルで初回読み込み時に音声がロードされない。
・mp4ファイルで長時間の動画の読み込みに時間がかかる、またはフリーズする。

**Comment by Mr-Ojii** [comment]
バグ報告ありがとうございます。

前者の問題は私の環境でも確認ができたため、調査いたします。

後者について、1つのIssueにつき1つの問題を扱いたいため、新たにIssueを立ててください。よろしくお願いいたします。
「長時間」とは具体的にどれくらいの時間でしょうか？
新たに立てたIssueで、具体的な動画の情報を教えていただけると非常に助かります。


この #4 ではwmvの音声ロード問題のみを扱います。

**Comment by SysVR** [comment]
・mp4ファイルで長時間の動画の読み込みに時間がかかる、またはフリーズする。
この件ですが、数分待っていたら読み込まれました。失礼しました。

**Comment by Mr-Ojii** [comment]
r1109で修正を試みました。ご確認ください。

**Comment by Mr-Ojii** [comment]
1ヶ月音沙汰がないため、Closeさせていただきます。

**Comment by SysVR** [comment]
遅れて申し訳ありません。
ただいまBuild-2024-02-17-01-15-42にて修正確認しました。
修正ありがとうございました。
