### ISSUE TITLE
【自己解決・Bugではなかったです】音声ファイルが読み込まれない・小音量のノイズに置き換わって音が出ない

### ISSUE THREAD

**Issue by Yu-yu0202** [Mr-Ojii/L-SMASH-Works#6]
Aviutl 本体Ver:1.10、
拡張編集Ver: 0.92
LSW Ver:r1118 (Mr-Ojii さんBuild）
patch.aui Ver:r43_ss_60
を使っている者です。
音声ファイルを読み込むと、（[ここ](https://scrapbox.io/aviutl/%E9%9F%B3%E3%81%8C%E9%B3%B4%E3%82%89%E3%81%AA%E3%81%84)参照）緑の線は表示されるが、音声がノイズに置き換わって音が鳴らない、といった現象が起きています。
確認したファイルは、
.mp3
.wav
.MOV です。
対処法等を教えていただけますと幸いです。

**Comment by Mr-Ojii** [comment]
不具合報告ありがとうございます。
原因究明のための情報が不足している状態であるため、以下の追加情報を教えていただけますでしょうか？

1. 確認した各ファイルについては全て単一プロジェクト内で、確認したものでしょうか？それとも、その都度プロジェクトを作成し、そのファイルのみを読み込ませたものでしょうか？
2. 確認したファイルはそれぞれ別々の音声ファイルでしょうか？それとも、単一のファイルを別形式に変換したものでしょうか？
3. 確認時には拡張編集に対して音声ファイルを読み込ませたのでしょうか？また、その場合はAviUtl本体に読み込ませた場合でも同様の現象が発生しますでしょうか？
4. 確認時のAviUtlの「その他」->「ファイルの情報」のダイアログ画像をご提示いただけますでしょうか？
5. それぞれ検証に使った音声ファイルのご提供は可能でしょうか？少しでも懸念事項がある場合などは、遠慮なく拒否していただいて構いません。
6. 5において、音声ファイル自体の提供が不可能である場合、それぞれの音声ファイルをMediaInfoに読み込ませ、表示される情報を送付していただくことは可能でしょうか？
7. 6において、MediaInfoで解析した情報の送付が不可能である場合、それぞれの音声ファイルの「チャンネル数」と「サンプリングレート」を教えていただくことは可能でしょうか

お手数ですが、よろしくお願いいたします。

**Comment by Yu-yu0202** [comment]
反応ありがとうございます。
（僕は小学生のため、返信時間がこの時間になってきてしまうのはご了承ください。書かれている内容についてはわかるので、そのままで大丈夫です。）
1.後者です。都度プロジェクトを作成して、読み込ませました。(1980x1080、60fps、320Hzの設定です。）
2.MOVファイルを、①そのまま読み込み→失敗 ②音声抽出してwavに変換→失敗 ③同じくmp3に変換→失敗
3.拡張編集です。
4.ffmpeg出力→ノイズに置き換わっています。設定:⇓
![image](https://github.com/Mr-Ojii/L-SMASH-Works/assets/135312165/c0b9eb3d-d5a3-4bc3-9a3f-a6ab275593be)

x264GUIEx→音が消えました 設定:⇓
![image](https://github.com/Mr-Ojii/L-SMASH-Works/assets/135312165/e4433dd5-72cf-4347-83da-740621a8654d)

5.
![image](https://github.com/Mr-Ojii/L-SMASH-Works/assets/135312165/675b50b8-8f48-410e-bd75-1207796ddba9)

6.友達の声が入っており、許可を取ることが難しいため、提供することができませんm(__)m
7.
```
ID                                       : 2
形式                                       : AAC LC
形式/情報                                    : Advanced Audio Codec Low Complexity
コーデック ID                                 : mp4a-40-2
長さ                                       : 22秒 735ミリ秒
元の長さ                                     : 22秒 802ミリ秒
ビットレート種別                                 : 可変 (VBR)
ビットレート                                   : 192 Kbps
チャンネル                                    : 2 チャンネル
チャンネルの配置                                 : L R
サンプルレート                                  : 44.1 KHz
フレームレート                                  : 43.066 fps (1024 SPF)
圧縮方法                                     : 非可逆
ストリームのサイズ                                : 528 KiB (1%)
元のストリームサイズ                               : 529 KiB (1%)
タイトル                                     : Core Media Audio
エンコード日                                   : 2024-07-10 04:27:05 UTC
タグ付け日                                    : 2024-07-10 04:27:29 UTC

その他 #1
ID                                       : 3
種類                                       : meta
形式                                       : mebx
コーデック ID                                 : mebx
長さ                                       : 22秒 735ミリ秒
ビットレート種別                                 : 固定 (CBR)
タイトル                                     : Core Media Metadata
エンコード日                                   : 2024-07-10 04:27:05 UTC
タグ付け日                                    : 2024-07-10 04:27:29 UTC

その他 #2
ID                                       : 4
種類                                       : meta
形式                                       : mebx
コーデック ID                                 : mebx
長さ                                       : 22秒 735ミリ秒
元の長さ                                     : 22秒 770ミリ秒
ビットレート種別                                 : 可変 (VBR)
ストリームのサイズ                                : 330 KiB
元のストリームサイズ                               : 330 KiB
タイトル                                     : Core Media Metadata
エンコード日                                   : 2024-07-10 04:27:05 UTC
タグ付け日                                    : 2024-07-10 04:27:29 UTC

その他 #3
ID                                       : 5
種類                                       : meta
形式                                       : mebx
コーデック ID                                 : mebx
長さ                                       : 22秒 735ミリ秒
ビットレート種別                                 : 可変 (VBR)
タイトル                                     : Core Media Metadata
エンコード日                                   : 2024-07-10 04:27:05 UTC
タグ付け日                                    : 2024-07-10 04:27:29 UTC

```
8.2ch 44100MHzです。

**Comment by Yu-yu0202** [comment]
自己解決しました。こちらのプラグインの問題ではなく、僕がサンプリングレートを誤って設定したことが原因でした。プロジェクト作成時に「320Hz」と言いましたが、「挿入した音声のサンプリングレート(Hz)」と、「動画ファイルで出力するときにしたい音声のレート（320KHz)」を間違っていました...
大変ご迷惑をおかけしました。申し訳ありません。

**Comment by Mr-Ojii** [comment]
自己解決できたのであれば、よかったです。

わざわざ多くの情報をお送りいただき、誠にありがとうございます。
今後の参考にさせていただきます。
ありがとうございました。
